#!/bin/bash

# needs to be in path and provides a 
# test_url url port {optional checkstring}
# interface so far

test_url () {


  checkcode=1
  i=12
  until [ $checkcode == 0 ]
  do
    checkcode=$(curl --connect-timeout 60 ${1}:${2}|grep ${3} > /dev/null;echo $?)
    i=$((i-1))
    if [[ $i == "1" ]]
      then
      echo 'timing out as took too long'
      break
    fi


    sleep 10
    # to make fail for test: sleep 5
  done


    if [[ $checkcode != "0" ]]
      then
      echo test failed for access to ${1}:${2}
    else
      echo test passed  for access to ${1}:${2}

    fi

    echo ${checkcode}

}




if [[ $# -lt 3 ]]; then
    echo "Not defined searchstring param so using 'Hello World'" >&2
    export search_string='Hello World'
    #exit 2
else search_string=$3
fi

echo ${search_string}


test_url $1 $2 ${search_string}


# unit test length of test
# values 
# parameters
# etc
# end to end 
# https check

# ./test_url http://dog.com 80 dog
# test passed

./test_url http://dog.com 80 dogd
# test timed out
